version: '3.9'

services:
  backend:
    container_name: backend
    image: backend
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "$NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT"
    environment:
      - DATABASE_URL=$MYSQLDATABASE_URL
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default
  db:
    container_name: db
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-db:/docker-entrypoint-initdb.d/
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - default
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default
volumes:
  dbdata: {}
networks:
  default: